Repository OpenCodeChicago/Midwest-Pumpkins, pull requests merged in 2024-10, with the labels that each got.

#51 Scroll to Top feature implemented
  src/js/scroll-up.js
  src/partials/scroll-up.html
  src/styles/scroll-up.css
Labels: hacktoberfest-accepted

#52 Add hero HTML and hero image
  public/images/hero_image.jpg
  src/partials/hero.html
Labels: hacktoberfest, hacktoberfest-accepted

#54 Added static text and preliminary styles
  src/partials/features.html
  src/styles/features.css
Labels: hacktoberfest-accepted

#57 add css for hero section
  src/partials/hero.html
  src/styles/hero.css
Labels: hacktoberfest, hacktoberfest-accepted

#64 Remove javascript and add href for top-sellers button, add id to top-sellers section
  src/partials/hero.html
  src/partials/top-sellers.html
  src/styles/hero.css
Labels: hacktoberfest, hacktoberfest-accepted

#65 Added images, text, and styling to the featured boxes
  public/images/decorative-mini-pumpkins1920x1080.png
  public/images/jack-o-lantern-pumpkin1920x1080.png
  public/images/sugar-pie-pumpkin1920x1080.png
  public/images/white-ghost-pumpkin1920x1080.png
  src/partials/features.html
  src/styles/features.css
Labels: hacktoberfest-accepted

#66 Daniel subscribe
  public/images/pumpkin-dark-background640-427.avif
  src/partials/subscribe.html
  src/styles/subscribe.css
Labels: hacktoberfest, hacktoberfest-accepted

#68 made css and html scoped more towards task of only subscribe section
  src/partials/subscribe.html
  src/styles/subscribe.css
Labels: hacktoberfest-accepted

#72 top sellers html
  src/partials/top-sellers.html
Labels: hacktoberfest, hacktoberfest-accepted

#73 Brian footer
  src/index.html
  src/partials/footer.html
  src/styles/footer.css
Labels: hacktoberfest-accepted

#76 add id of topseller section
  src/partials/top-sellers.html
Labels: hacktoberfest, hacktoberfest-accepted

#77 Victor/buy now popup
  src/partials/buy-now-modal.html
  src/styles/buy-now-modal.css
Labels: hacktoberfest, hacktoberfest-accepted

#78 Scroll up functinality full implemented
  public/images/Scroll-up.svg
  src/js/scroll-up.js
  src/partials/scroll-up.html
  src/styles/scroll-up.css
Labels: hacktoberfest-accepted

#79 Feature- Scroll to top
  src/main.js
  src/partials/scroll-up.html
  src/styles/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#83 added sprite.svg
  package-lock.json
  package.json
  sprite.svg
  src/index.html
  src/partials/footer.html
  src/partials/scroll-up.html
Labels: hacktoberfest-accepted

#86 Update breakpoints and some css
  src/styles/hero.css
Labels: hacktoberfest, hacktoberfest-accepted

#87 added the icon
  public/images/Vector.png
  src/index.html
Labels: hacktoberfest-accepted

#91 About us section
  public/images/logo1.png
  public/images/logo2.png
  public/images/logo3.png
  src/partials/about.html
  src/styles/about.css
Labels: hacktoberfest-accepted

#92 Added hover effect on featured pumpkins blocks and fixed css page to use variables.
  src/js/features.js
  src/main.js
  src/partials/features.html
  src/styles/features.css
Labels: hacktoberfest-accepted

#93 Added html and css for mobile nav burger menu.
  public/images/pumpkin.svg
  public/sprite.svg
  src/partials/burger-menu.html
  src/partials/header.html
  src/styles/burger-menu.css
  src/styles/header.css
  src/styles/style.css
Labels: hacktoberfest-accepted

#94 changed the favicon png to svg
  public/Vector.svg
  public/images/Vector.png
  public/vite.svg
  src/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#95 Added responsive mobile behavior to flexbox.
  public/images/decorative-mini-pumpkins1920x1080.png
  public/images/decorative-mini-pumpkins1920x1080.svg
  public/images/jack-o-lantern-pumpkin1920x1080.png
  public/images/jack-o-lantern-pumpkin1920x1080.svg
  public/images/sugar-pie-pumpkin1920x1080.png
  public/images/sugar-pie-pumpkin1920x1080.svg
  public/images/white-ghost-pumpkin1920x1080.png
  public/images/white-ghost-pumpkin1920x1080.svg
  src/partials/features.html
  src/styles/features.css
Labels: hacktoberfest-accepted

#98 Added the Top-Seller Section responsive Layout
  package-lock.json
  public/images/Top-Seller-img1.png
  public/images/Top-Seller-img2.png
  public/images/Top-Seller-img3.png
  src/partials/top-sellers.html
  src/styles/top-sellers.css
Labels: hacktoberfest-accepted

#99 Implemented notification system
  src/index.html
  src/js/buy-now-modal.js
  src/js/header.js
  src/js/reviews-modal.js
  src/js/subscribe-modal.js
  src/main.js
  src/partials/buy-now-modal.html
  src/partials/reviews-modal.html
  src/partials/subscribe-modal.html
Labels: hacktoberfest-accepted

#101 User Reviews Integration
  public/images/Profile1.png
  public/images/profile2.png
  public/images/profile3.png
  src/js/review.js
  src/js/reviews-modal.js
  src/main.js
  src/partials/reviews-modal.html
  src/partials/reviews.html
  src/styles/reviews-modal.css
  src/styles/reviews.css
Labels: hacktoberfest-accepted

#102 Add Responsiveness
  src/partials/features.html
  src/styles/about.css
  src/styles/features.css
  src/styles/footer.css
  src/styles/hero.css
  src/styles/subscribe.css
Labels: hacktoberfest-accepted

#104 add javascript for open/close buy-now popup
  src/js/buy-now-modal.js
Labels: hacktoberfest, hacktoberfest-accepted

#105 Move inline svgs in header and burger menu to sprite.svg. Update html…
  public/sprite.svg
  src/partials/burger-menu.html
  src/partials/header.html
  src/styles/burger-menu.css
  src/styles/header.css
Labels: hacktoberfest-accepted

#106 add social icons and menu links
  public/images/mdi_facebook.svg
  public/images/mdi_github.svg
  public/images/mdi_linkedin.svg
  public/images/mdi_twitter.svg
  public/images/mdi_youtube.svg
  src/partials/header.html
Labels: hacktoberfest, hacktoberfest-accepted

#108 Replaced onmouseover with hover for the featured pumpkin cards.
  src/js/features.js
  src/main.js
  src/partials/features.html
  src/styles/features.css
Labels: hacktoberfest-accepted

#109 Update footer layout for desktop, tablet, and mobile based on Figma d…
  src/partials/footer.html
  src/styles/footer.css
  src/styles/top-sellers.css
Labels: hacktoberfest-accepted

#110 Fixed clashing css class names affecting the location of text. Adjusted responsiveness to use flex-wrap.
  src/partials/features.html
  src/styles/features.css
Labels: hacktoberfest-accepted

#111 Fixed html/css conflicts to hide/show desktop/mobile nav.
  src/partials/about.html
  src/partials/features.html
  src/partials/header.html
  src/partials/reviews.html
  src/partials/top-sellers.html
  src/styles/burger-menu.css
  src/styles/features.css
  src/styles/header.css
Labels: hacktoberfest-accepted

#112 styling added, but not done
  src/partials/buy-now-modal.html
  src/styles/buy-now-modal.css
Labels: hacktoberfest, hacktoberfest-accepted

#113 Add Responsivness
  src/styles/burger-menu.css
  src/styles/features.css
  src/styles/reviews.css
  src/styles/subscribe.css
  src/styles/top-sellers.css
Labels: hacktoberfest, hacktoberfest-accepted

#115 Daniel subscribe modal
  public/images/subscribe-Pumpkin-pile.avif
  public/images/x-close.svg
  src/js/subscribe-modal.js
  src/partials/subscribe-modal.html
  src/partials/subscribe.html
  src/styles/subscribe-modal.css
  src/styles/subscribe.css
Labels: hacktoberfest

#116 update the review slider section and add carousel features
  src/js/slider.js
  src/partials/reviews.html
  src/partials/top-sellers.html
  src/styles/reviews.css
  src/styles/top-sellers.css
Labels: hacktoberfest, hacktoberfest-accepted

#117 fix the modal problem in the subscribe section when the user clicks t…
  src/js/buy-now-modal.js
  src/js/subscribe-modal.js
  src/partials/subscribe-modal.html
  src/partials/subscribe.html
  src/styles/subscribe-modal.css
  src/styles/subscribe.css
Labels: hacktoberfest, hacktoberfest-accepted

#118 fix the slider not showing problem by removing class collision
  src/partials/reviews.html
  src/styles/reviews.css
Labels: hacktoberfest, hacktoberfest-accepted

#119 Added js for burger menu. Updated html/css for slideout menu.
  src/js/burger-menu.js
  src/js/header.js
  src/main.js
  src/partials/burger-menu.html
  src/partials/header.html
  src/partials/reviews.html
  src/styles/burger-menu.css
  src/styles/header.css
Labels: hacktoberfest, hacktoberfest-accepted

#120 Dark Mode with local storage functionality added
  public/dark-mode.svg
  src/js/dark-theme.js
  src/main.js
  src/partials/header.html
  src/styles/header.css
  src/styles/style.css
  src/styles/top-sellers.css
Labels: hacktoberfest, hacktoberfest-accepted

#121 responsive about us
  src/styles/about.css
Labels: hacktoberfest, hacktoberfest-accepted

#123 Dark theme - visibility issue fixed
  src/partials/features.html
  src/partials/header.html
  src/partials/reviews.html
  src/partials/top-sellers.html
  src/styles/features.css
  src/styles/header.css
Labels: hacktoberfest, hacktoberfest-accepted

#124 Escape button close feature add
  src/js/subscribe-modal.js
Labels: hacktoberfest, hacktoberfest-accepted

#125 Bugfix/header dark light colors
  src/partials/header.html
  src/styles/burger-menu.css
  src/styles/header.css
Labels: hacktoberfest, hacktoberfest-accepted

#126 need to style phone number and card number. make it phone and tablet …
  src/js/buy-now-modal.js
  src/partials/buy-now-modal.html
  src/styles/buy-now-modal.css
Labels: hacktoberfest, hacktoberfest-accepted

#128 Modal email input validation with pattern attribute
  src/partials/subscribe-modal.html
Labels: hacktoberfest, hacktoberfest-accepted

#129 Made font size changes to so text does not cut off in mobile view.
  src/partials/features.html
  src/styles/features.css
Labels: hacktoberfest, hacktoberfest-accepted

#130 Fixed responsiveness for mobile hovering.
  src/js/features.js
  src/main.js
  src/styles/features.css
Labels: hacktoberfest, hacktoberfest-accepted

#131 Daniel subscribe modal
  src/js/subscribe-modal.js
  src/styles/subscribe-modal.css
Labels: hacktoberfest, hacktoberfest-accepted

#133 Bug fix of disappearing x, modal closes now upon pressing esc key
  src/js/subscribe-modal.js
Labels: hacktoberfest, hacktoberfest-accepted

#134 Daniel subscribe modal
  src/styles/subscribe-modal.css
Labels: hacktoberfest, hacktoberfest-accepted

#135 Fixed footer layout issues, updated social media links and removed in…
  src/partials/burger-menu.html
  src/partials/footer.html
  src/partials/header.html
  src/styles/footer.css
Labels: hacktoberfest, hacktoberfest-accepted

#136 javascript portion works now, the css responsiveness needs work
  src/js/buy-now-modal.js
  src/partials/buy-now-modal.html
  src/styles/buy-now-modal.css
Labels: hacktoberfest, hacktoberfest-accepted

#138 Updated html/css for reviews modal.
  public/images/us-flag-icon.png
  src/partials/reviews-modal.html
  src/styles/reviews-modal.css
Labels: hacktoberfest, hacktoberfest-accepted

#140 Updated all font sizes in features section to match the font sizes in figma design
  src/partials/features.html
  src/styles/features.css
Labels: hacktoberfest, hacktoberfest-accepted

#141 Solved outside click buy now popup close
  src/js/buy-now-modal.js
  src/styles/buy-now-modal.css
  src/styles/header.css
Labels: hacktoberfest, hacktoberfest-accepted

#142 Changed responsiveness of featured boxes.
  src/partials/features.html
  src/styles/features.css
Labels: hacktoberfest, hacktoberfest-accepted

#143 Updated Feature section description to match the font size and line height of the "About" section.
  src/styles/features.css
Labels: hacktoberfest, hacktoberfest-accepted

#144 Fourth card color needed fixing.
  src/styles/features.css
  src/styles/reviews.css
  src/styles/subscribe.css
  src/styles/top-sellers.css
Labels: hacktoberfest, hacktoberfest-accepted

#145 Fixed some of the Buy Now modal styles.
  src/partials/buy-now-modal.html
  src/styles/buy-now-modal.css
Labels: hacktoberfest, hacktoberfest-accepted

#147 Add form validation to reviews modal. Update html/css for error messa…
  src/js/reviews-modal.js
  src/partials/reviews-modal.html
  src/styles/reviews-modal.css
Labels: hacktoberfest, hacktoberfest-accepted
